const robots=[
 {id:"warehouse-01",name:"RoboCarry X2",cat:"warehouse",catName:"KHO VẬN",icon:"🤖",desc:"Đội vận chuyển tự hành cho kho và nhà máy.",price:850000,rating:"4.9",place:"SHENZHEN / CN",tag:"CORE UNIT"},
 {id:"service-01",name:"ServiBot S1",cat:"service",catName:"DỊCH VỤ",icon:"🦾",desc:"Tương tác khách hàng và giao món tự động.",price:1200000,rating:"4.8",place:"HANOI / VN",tag:"READY NOW"},
 {id:"industrial-01",name:"ArmFlex 6A",cat:"industrial",catName:"CÔNG NGHIỆP",icon:"🦿",desc:"Cánh tay 6 trục cho dây chuyền sản xuất.",price:2800000,rating:"5.0",place:"SHANGHAI / CN",tag:"VERIFIED"},
 {id:"event-01",name:"GuideBot Pro",cat:"event",catName:"SỰ KIỆN",icon:"🧑‍🚀",desc:"Robot lễ tân và tương tác tại sự kiện.",price:1600000,rating:"4.7",place:"HCMC / VN",tag:"NEW UNIT"},
 {id:"warehouse-02",name:"CleanRoute C3",cat:"warehouse",catName:"KHO VẬN",icon:"🛞",desc:"Lau sàn công nghiệp tự động, pin 8 giờ.",price:650000,rating:"4.8",place:"GUANGZHOU / CN",tag:"EFFICIENT"},
 {id:"service-02",name:"RoomMate R4",cat:"service",catName:"DỊCH VỤ",icon:"🧹",desc:"Giao đồ và phục vụ phòng tự động.",price:980000,rating:"4.6",place:"DANANG / VN",tag:"READY NOW"}
];
const state={cat:"all",query:"",orders:JSON.parse(localStorage.getItem("nexa-orders")||"[]")};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat("vi-VN").format(n)+" đ";
function renderRobots(){const items=robots.filter(r=>(state.cat==="all"||r.cat===state.cat)&&`${r.name} ${r.desc} ${r.catName}`.toLowerCase().includes(state.query.toLowerCase()));$("#robotGrid").innerHTML=items.length?items.map(r=>`<article class="robot-card"><div class="robot-photo"><span>${r.icon}</span><em class="tag">${r.tag}</em></div><div class="robot-info"><h3>${r.name}</h3><p>${r.desc}</p><div class="robot-meta"><div><div class="price">${money(r.price)} <small>/ NGÀY</small></div><small>★ ${r.rating} · ${r.place}</small></div><div class="card-actions"><button class="detail-button" data-id="${r.id}">CHI TIẾT</button><button class="rent-button" data-id="${r.id}">THUÊ ↗</button></div></div></div></article>`).join(""):`<div class="empty-state">NO UNITS MATCH YOUR QUERY.</div>`;document.querySelectorAll(".rent-button").forEach(b=>b.onclick=()=>booking(b.dataset.id));document.querySelectorAll(".detail-button").forEach(b=>b.onclick=()=>details(b.dataset.id))}
function details(id){const r=robots.find(x=>x.id===id);show(`<div class="kicker">UNIT PROFILE / ${r.catName}</div><h2>${r.name}<br><span>Thông số triển khai.</span></h2><div class="detail-hero"><span>${r.icon}</span><div><b>${r.tag}</b><small>★ ${r.rating} · ${r.place}</small></div></div><div class="spec-grid"><div><small>NHIỆM VỤ</small><b>${r.desc}</b></div><div><small>GIÁ THAM CHIẾU</small><b>${money(r.price)} / ngày</b></div><div><small>TRẠNG THÁI</small><b class="lime">SẴN SÀNG</b></div><div><small>HỖ TRỢ</small><b>Giao · lắp đặt · thu hồi</b></div></div><button class="neon-button" id="detailRent">ĐẶT THUÊ ĐƠN VỊ ↗</button>`);$("#detailRent").onclick=()=>booking(r.id)}
function show(html){$("#modalContent").innerHTML=html;$("#modalBackdrop").classList.remove("hidden")}function hide(){$("#modalBackdrop").classList.add("hidden")}
function booking(id){const r=robots.find(x=>x.id===id);show(`<div class="kicker">UNIT RESERVATION / ${r.catName}</div><h2>Đặt thuê<br><span>${r.name}</span></h2><p class="modal-intro">${r.desc} Đối tác vận chuyển, lắp đặt và thu hồi robot theo mã hợp đồng.</p><form id="bookForm"><div class="form-grid"><div class="field"><label>NGÀY BẮT ĐẦU</label><input required type="date" id="start"></div><div class="field"><label>THỜI LƯỢNG (NGÀY)</label><input required min="1" value="7" type="number" id="days"></div><div class="field full"><label>ĐỊA ĐIỂM TRIỂN KHAI</label><input required id="address" placeholder="Địa chỉ giao robot"></div><div class="field full"><label>NGƯỜI PHỤ TRÁCH</label><input required id="contact" placeholder="Họ tên · Số điện thoại"></div></div><div class="summary"><span>ESTIMATED TOTAL</span><strong id="total">${money(r.price*7)}</strong></div><button class="neon-button" type="submit">TIẾP TỤC THANH TOÁN ↗</button></form>`);$("#start").value=new Date().toISOString().slice(0,10);$("#days").oninput=e=>$("#total").textContent=money(r.price*Math.max(1,Number(e.target.value)||1));$("#bookForm").onsubmit=e=>{e.preventDefault();payment(r)}}
function payment(r){const days=Number($("#days").value),total=r.price*days;show(`<div class="kicker">SECURE CHECKOUT / SANDBOX</div><h2>Kích hoạt<br><span>hợp đồng.</span></h2><p class="modal-intro">Thanh toán mô phỏng. Khi kết nối thật, cổng marketplace sẽ giữ tiền và giải ngân theo điều kiện hợp đồng.</p><div class="summary"><span>${r.name} · ${days} NGÀY</span><strong>${money(total)}</strong></div><div class="field"><label>PHƯƠNG THỨC THANH TOÁN</label><select><option>THẺ QUỐC TẾ / SANDBOX</option><option>VÍ ĐIỆN TỬ / SANDBOX</option><option>CHUYỂN KHOẢN / SANDBOX</option></select></div><button class="neon-button" id="pay">XÁC NHẬN ${money(total)} ↗</button>`);$("#pay").onclick=()=>createOrder(r,days,total)}
function createOrder(r,days,total){const code=`NX-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;state.orders.unshift({code,robot:r.name,days,total,date:new Date().toLocaleDateString("vi-VN"),status:"ĐANG VẬN HÀNH",receipt:""});localStorage.setItem("nexa-orders",JSON.stringify(state.orders));renderOrders();show(`<div class="success-box">✓ PAYMENT CONFIRMED<br><span>Đơn hàng đã gửi cho đối tác để chuẩn bị giao robot.</span></div><div class="kicker">CONTRACT IDENTIFIER</div><div class="contract-code">${code}</div><p class="modal-intro">Lưu mã hợp đồng. Đối tác phải xuất trình giấy xác nhận và mã này khi đến thu robot.</p><button class="neon-button" id="goOrders">XEM HỢP ĐỒNG ↓</button>`);$("#goOrders").onclick=()=>{hide();$("#orders").scrollIntoView()}}
function renderOrders(){const list=$("#ordersList");if(!state.orders.length){list.innerHTML='<div class="empty-state">NO ACTIVE CONTRACTS / Chọn một đơn vị để bắt đầu.</div>'}else{list.innerHTML=state.orders.map((o,i)=>`<article class="order-card"><div><h3>${o.robot}</h3><p>CONTRACT <strong>${o.code}</strong> · ${o.days} DAYS · ${o.date}</p>${o.receipt?`<p style="color:#ffb45d;margin-top:8px">PICKUP RECEIPT <strong>${o.receipt}</strong></p>`:""}</div><div class="order-actions"><span class="status">${o.status}</span>${o.receipt?"":`<button class="danger-button" data-index="${i}">CHẤM DỨT ↗</button>`}</div></article>`).join("");document.querySelectorAll(".danger-button").forEach(b=>b.onclick=()=>terminate(Number(b.dataset.index)))}renderAccount();renderAdmin()}
function renderAccount(){const profile=JSON.parse(localStorage.getItem("nexa-profile")||"null");if(profile){$("#accountName").textContent=profile.name;$("#accountEmail").textContent=profile.email}$("#accountOrders").textContent=state.orders.length;$("#accountActive").textContent=state.orders.filter(o=>!o.receipt).length;$("#accountClosed").textContent=state.orders.filter(o=>o.receipt).length}
function renderAdmin(){$("#adminRobotCount").textContent=`${robots.length.toString().padStart(2,"0")} UNITS`;$("#adminOrderCount").textContent=`${state.orders.length.toString().padStart(2,"0")} ORDERS`;$("#adminRobots").innerHTML=robots.map(r=>`<div class="admin-row"><span>${r.icon}</span><b>${r.name}</b><small>${r.catName}</small><i>ACTIVE</i></div>`).join("");$("#adminOrders").innerHTML=state.orders.length?state.orders.map(o=>`<div class="admin-row"><span>↗</span><b>${o.code}</b><small>${o.robot}</small><i>${o.status}</i></div>`).join(""):'<div class="admin-empty">Chưa có đơn hàng.</div>'}
function terminate(i){const o=state.orders[i];show(`<div class="kicker">PICKUP REQUEST / ${o.code}</div><h2>Phát hành<br><span>phiếu thu hồi?</span></h2><p class="modal-intro">Khách hàng xác nhận chấm dứt. NEXA sẽ phát hành phiếu cho cả hai bên. Đối tác phải xuất trình giấy xác nhận và mã hợp đồng khi đến thu.</p><div class="summary"><span>CONTRACT</span><strong>${o.code}</strong></div><button class="neon-button" id="confirm">PHÁT HÀNH PHIẾU THU HỒI ↗</button>`);$("#confirm").onclick=()=>{const receipt=`PK-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;o.receipt=receipt;o.status="CHỜ ĐỐI TÁC THU HỒI";localStorage.setItem("nexa-orders",JSON.stringify(state.orders));renderOrders();show(`<div class="success-box">✓ PICKUP PROTOCOL ISSUED<br><span>Thông tin đã gửi cho khách hàng và đối tác.</span></div><div class="receipt">MÃ PHIẾU THU HỒI<br><strong>${receipt}</strong><br><br>MÃ HỢP ĐỒNG ĐỐI CHIẾU<br><strong>${o.code}</strong><br><br>Đối tác xuất trình giấy xác nhận + mã hợp đồng khi đến thu.</div><button class="neon-button" id="done">ĐÃ HIỂU</button>`);$("#done").onclick=hide}}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{state.cat=b.dataset.category;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderRobots()});$("#searchInput").oninput=e=>{state.query=e.target.value;renderRobots()};$("#closeModal").onclick=hide;$("#modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")hide()};
$("#openPartner").onclick=()=>show(`<div class="kicker">PARTNER ONBOARDING</div><h2>Kết nối<br><span>đội robot.</span></h2><p class="modal-intro">Gửi thông tin đơn vị. NEXA sẽ xác minh năng lực, cấu hình vận chuyển và hợp đồng thu hồi.</p><div class="field"><label>TÊN CÔNG TY</label><input placeholder="Tên doanh nghiệp"></div><div class="field"><label>EMAIL LIÊN HỆ</label><input type="email" placeholder="ops@company.com"></div><button class="neon-button" id="partnerSubmit">GỬI ĐĂNG KÝ ↗</button>`);
$("#editAccount").onclick=()=>show(`<div class="kicker">RENTER PROFILE</div><h2>Cập nhật<br><span>tài khoản.</span></h2><div class="field"><label>HỌ TÊN / TÊN DOANH NGHIỆP</label><input id="profileName" placeholder="Nguyễn Văn A"></div><div class="field"><label>EMAIL NHẬN THÔNG BÁO</label><input id="profileEmail" type="email" placeholder="you@company.com"></div><button class="neon-button" id="saveProfile">LƯU HỒ SƠ ↗</button>`);
$("#openAssistant").onclick=()=>show(`<div class="kicker">NEXA AI / BASIC ASSISTANT</div><h2>Trợ lý<br><span>triển khai robot.</span></h2><p class="modal-intro">Tôi có thể gợi ý nhanh mô hình phù hợp dựa trên nhu cầu của bạn.</p><div class="field"><label>BẠN MUỐN THỰC HIỆN VIỆC GÌ?</label><input id="aiQuestion" placeholder="Ví dụ: cần robot cho kho 7 ngày"></div><button class="neon-button" id="askAi">PHÂN TÍCH NHU CẦU ↗</button><div id="aiAnswer"></div>`);
document.addEventListener("click",e=>{if(e.target.id==="partnerSubmit"){hide();toast("✓ Đã nhận đăng ký đối tác.")}if(e.target.id==="saveProfile"){const profile={name:$("#profileName").value.trim()||"Khách hàng NEXA",email:$("#profileEmail").value.trim()||"Chưa cập nhật email"};localStorage.setItem("nexa-profile",JSON.stringify(profile));renderAccount();hide();toast("✓ Hồ sơ đã được cập nhật.")}if(e.target.id==="askAi"){const q=$("#aiQuestion").value.toLowerCase();const result=q.includes("kho")||q.includes("vận chuyển")?robots.find(r=>r.id==="warehouse-01"):q.includes("nhà hàng")||q.includes("phục vụ")?robots.find(r=>r.id==="service-01"):q.includes("sản xuất")||q.includes("công nghiệp")?robots.find(r=>r.id==="industrial-01"):robots[0];$("#aiAnswer").innerHTML=`<div class="ai-answer">GỢI Ý ĐƠN VỊ<br><strong>${result.icon} ${result.name}</strong><br><small>${result.desc} Giá tham chiếu ${money(result.price)}/ngày.</small><button class="detail-button ai-rent" data-id="${result.id}">XEM CHI TIẾT ↗</button></div>`;document.querySelector(".ai-rent").onclick=()=>details(result.id)}});
function toast(message){$("#toast").textContent=message;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),3000)}
renderRobots();renderOrders();
