const translations={
 vi:{navFleet:"Đội robot",navProtocol:"Quy trình",navOrders:"Hợp đồng",navAccount:"Tài khoản",navAdmin:"Quản trị",partnerRegister:"+ Đăng ký đối tác",heroDescription:"Truy cập đội robot toàn cầu theo nhu cầu. Chọn mô hình, đặt lịch vận hành — đối tác giao tận nơi và thu hồi theo mã hợp đồng.",exploreFleet:"KHÁM PHÁ ĐỘI ROBOT ↗",viewProtocol:"Xem giao thức ↓",fleetTitle:"Chọn đơn vị<br><span>phù hợp.</span>",fleetNote:"Mỗi robot được xác minh bởi NEXA<br>và sẵn sàng triển khai theo hợp đồng.",contractsTitle:"Hợp đồng<br><span>đang hoạt động.</span>",all:"TẤT CẢ",details:"CHI TIẾT",rent:"THUÊ ↗",day:"NGÀY",search:"Tìm mã đơn vị hoặc nhiệm vụ",empty:"Không tìm thấy đơn vị phù hợp."},
 en:{navFleet:"Robot fleet",navProtocol:"Protocol",navOrders:"Contracts",navAccount:"Account",navAdmin:"Admin",partnerRegister:"+ Partner signup",heroDescription:"Access a global robot fleet on demand. Choose a model, schedule deployment — partners deliver and collect by contract code.",exploreFleet:"EXPLORE ROBOT FLEET ↗",viewProtocol:"View protocol ↓",fleetTitle:"Choose the<br><span>right unit.</span>",fleetNote:"Every robot is verified by NEXA<br>and ready for contract deployment.",contractsTitle:"Active<br><span>contracts.</span>",all:"ALL",details:"DETAILS",rent:"RENT ↗",day:"DAY",search:"Search unit or task",empty:"NO UNITS MATCH YOUR QUERY."},
 zh:{navFleet:"机器人队伍",navProtocol:"服务流程",navOrders:"合同",navAccount:"账户",navAdmin:"管理",partnerRegister:"+ 注册合作伙伴",heroDescription:"按需使用全球机器人队伍。选择型号并安排部署，合作伙伴按合同编码配送和回收。",exploreFleet:"探索机器人 ↗",viewProtocol:"查看流程 ↓",fleetTitle:"选择<br><span>合适的设备。</span>",fleetNote:"每台机器人均经 NEXA 验证<br>可按合同部署。",contractsTitle:"正在运行的<br><span>合同。</span>",all:"全部",details:"详情",rent:"租用 ↗",day:"天",search:"搜索设备或任务",empty:"没有匹配的设备。"},
 ru:{navFleet:"Роботы",navProtocol:"Процесс",navOrders:"Договоры",navAccount:"Аккаунт",navAdmin:"Админ",partnerRegister:"+ Стать партнёром",heroDescription:"Получайте доступ к роботам по всему миру. Выберите модель и график — партнёр доставит и заберёт робота по коду договора.",exploreFleet:"ОТКРЫТЬ СПИСОК РОБОТОВ ↗",viewProtocol:"Посмотреть процесс ↓",fleetTitle:"Выберите<br><span>подходящую модель.</span>",fleetNote:"Каждый робот проверен NEXA<br>и готов к работе по договору.",contractsTitle:"Активные<br><span>договоры.</span>",all:"ВСЕ",details:"ПОДРОБНОСТИ",rent:"АРЕНДОВАТЬ ↗",day:"ДЕНЬ",search:"Поиск модели или задачи",empty:"ПОДХОДЯЩИХ МОДЕЛЕЙ НЕТ."},
 fr:{navFleet:"Robots",navProtocol:"Processus",navOrders:"Contrats",navAccount:"Compte",navAdmin:"Admin",partnerRegister:"+ Devenir partenaire",heroDescription:"Accédez à un parc mondial de robots à la demande. Choisissez un modèle et planifiez — le partenaire livre et récupère selon le contrat.",exploreFleet:"DÉCOUVRIR LES ROBOTS ↗",viewProtocol:"Voir le processus ↓",fleetTitle:"Choisissez<br><span>la bonne unité.</span>",fleetNote:"Chaque robot est vérifié par NEXA<br>et prêt à être déployé.",contractsTitle:"Contrats<br><span>actifs.</span>",all:"TOUS",details:"DÉTAILS",rent:"LOUER ↗",day:"JOUR",search:"Rechercher un robot ou une tâche",empty:"AUCUN ROBOT CORRESPONDANT."},
 de:{navFleet:"Roboter",navProtocol:"Ablauf",navOrders:"Verträge",navAccount:"Konto",navAdmin:"Admin",partnerRegister:"+ Partner werden",heroDescription:"Greifen Sie bei Bedarf auf eine globale Roboterflotte zu. Modell und Einsatz wählen — Partner liefern und holen nach Vertragscode ab.",exploreFleet:"ROBOTERFLOTTE ENTDECKEN ↗",viewProtocol:"Ablauf ansehen ↓",fleetTitle:"Die passende<br><span>Einheit wählen.</span>",fleetNote:"Jeder Roboter ist von NEXA geprüft<br>und vertragsbereit.",contractsTitle:"Aktive<br><span>Verträge.</span>",all:"ALLE",details:"DETAILS",rent:"MIETEN ↗",day:"TAG",search:"Roboter oder Aufgabe suchen",empty:"KEINE PASSENDEN ROBOTER."},
 th:{navFleet:"กองหุ่นยนต์",navProtocol:"ขั้นตอน",navOrders:"สัญญา",navAccount:"บัญชี",navAdmin:"ผู้ดูแล",partnerRegister:"+ สมัครพาร์ทเนอร์",heroDescription:"เข้าถึงหุ่นยนต์ทั่วโลกตามความต้องการ เลือกรุ่นและกำหนดเวลา พาร์ทเนอร์จะจัดส่งและรับคืนตามรหัสสัญญา",exploreFleet:"สำรวจกองหุ่นยนต์ ↗",viewProtocol:"ดูขั้นตอน ↓",fleetTitle:"เลือก<br><span>หุ่นยนต์ที่เหมาะสม</span>",fleetNote:"หุ่นยนต์ทุกตัวผ่านการตรวจสอบโดย NEXA<br>พร้อมใช้งานตามสัญญา",contractsTitle:"สัญญา<br><span>ที่กำลังดำเนินการ</span>",all:"ทั้งหมด",details:"รายละเอียด",rent:"เช่า ↗",day:"วัน",search:"ค้นหารุ่นหรืองาน",empty:"ไม่พบหุ่นยนต์ที่ตรงกัน"}
};
const sharedLabels={
 vi:{warehouse:"KHO VẬN",service:"DỊCH VỤ",industrial:"CÔNG NGHIỆP",event:"SỰ KIỆN",stepChoose:"CHỌN ĐƠN VỊ",stepChooseText:"Lọc theo nhiệm vụ, vị trí và thời lượng. Mọi thông số vận hành hiển thị trước khi đặt.",stepDeploy:"GIAO & KÍCH HOẠT",stepDeployText:"Đối tác vận chuyển, lắp đặt và bàn giao robot tận nơi theo lịch trong hợp đồng.",stepReturn:"THU HỒI XÁC THỰC",stepReturnText:"Nhấn chấm dứt. NEXA phát hành phiếu thu hồi, đối chiếu mã hợp đồng khi nhận robot."},
 en:{warehouse:"WAREHOUSE",service:"SERVICE",industrial:"INDUSTRIAL",event:"EVENT",stepChoose:"CHOOSE A UNIT",stepChooseText:"Filter by task, location and duration. See all operating details before booking.",stepDeploy:"DELIVER & ACTIVATE",stepDeployText:"The partner delivers, installs and hands over the robot at the scheduled location.",stepReturn:"VERIFIED RETURN",stepReturnText:"End the contract to issue a pickup receipt and verify the contract code at collection."},
 zh:{warehouse:"仓储",service:"服务",industrial:"工业",event:"活动",stepChoose:"选择设备",stepChooseText:"按任务、位置和时长筛选，预订前查看完整运行参数。",stepDeploy:"配送与启动",stepDeployText:"合作伙伴按合同安排配送、安装并交付机器人。",stepReturn:"验证回收",stepReturnText:"结束合同后生成回收凭证，并在取回时核对合同编码。"},
 ru:{warehouse:"СКЛАД",service:"СЕРВИС",industrial:"ПРОМЫШЛЕННОСТЬ",event:"СОБЫТИЯ",stepChoose:"ВЫБРАТЬ МОДЕЛЬ",stepChooseText:"Фильтр по задаче, месту и сроку. Все параметры видны до заказа.",stepDeploy:"ДОСТАВКА И ЗАПУСК",stepDeployText:"Партнёр доставит, установит и передаст робота по графику договора.",stepReturn:"ПРОВЕРЕННЫЙ ВОЗВРАТ",stepReturnText:"Завершите договор, чтобы получить квитанцию и проверить код при возврате."},
 fr:{warehouse:"ENTREPÔT",service:"SERVICE",industrial:"INDUSTRIE",event:"ÉVÉNEMENT",stepChoose:"CHOISIR UNE UNITÉ",stepChooseText:"Filtrez par tâche, lieu et durée. Consultez les paramètres avant de réserver.",stepDeploy:"LIVRER ET ACTIVER",stepDeployText:"Le partenaire livre, installe et remet le robot selon le contrat.",stepReturn:"RETOUR VÉRIFIÉ",stepReturnText:"Terminez le contrat pour émettre le reçu et vérifier le code lors de la reprise."},
 de:{warehouse:"LAGER",service:"SERVICE",industrial:"INDUSTRIE",event:"EVENT",stepChoose:"EINHEIT WÄHLEN",stepChooseText:"Nach Aufgabe, Ort und Dauer filtern. Alle Daten vor der Buchung prüfen.",stepDeploy:"LIEFERN & AKTIVIEREN",stepDeployText:"Der Partner liefert, installiert und übergibt den Roboter nach Vertragsplan.",stepReturn:"GEPRÜFTE RÜCKGABE",stepReturnText:"Vertrag beenden, Abholbeleg ausstellen und Vertragscode bei Abholung prüfen."},
 th:{warehouse:"คลังสินค้า",service:"บริการ",industrial:"อุตสาหกรรม",event:"อีเวนต์",stepChoose:"เลือกหุ่นยนต์",stepChooseText:"กรองตามงาน สถานที่ และระยะเวลา ดูข้อมูลทั้งหมดก่อนจอง",stepDeploy:"จัดส่งและเริ่มใช้งาน",stepDeployText:"พาร์ทเนอร์จัดส่ง ติดตั้ง และส่งมอบหุ่นยนต์ตามสัญญา",stepReturn:"รับคืนที่ตรวจสอบแล้ว",stepReturnText:"สิ้นสุดสัญญาเพื่อออกใบรับคืนและตรวจสอบรหัสสัญญาเมื่อรับหุ่นยนต์"}
};
Object.keys(sharedLabels).forEach(key=>Object.assign(translations[key],sharedLabels[key]));
let language=localStorage.getItem("nexa-language")||"vi";
function t(key){return (translations[language]||translations.vi)[key]||translations.vi[key]||key}
function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll("[data-i18n]").forEach(el=>el.innerHTML=t(el.dataset.i18n));const select=$("#languageSelect");if(select)select.value=language;const search=$("#searchInput");if(search)search.placeholder=t("search");renderRobots()}
const robots=[
 {id:"warehouse-01",name:"RoboCarry X2",cat:"warehouse",catName:"KHO VẬN",icon:"🤖",desc:"Đội vận chuyển tự hành cho kho và nhà máy.",price:850000,rating:"4.9",place:"SHENZHEN / CN",tag:"CORE UNIT"},
 {id:"service-01",name:"ServiBot S1",cat:"service",catName:"DỊCH VỤ",icon:"🦾",desc:"Tương tác khách hàng và giao món tự động.",price:1200000,rating:"4.8",place:"HANOI / VN",tag:"READY NOW"},
 {id:"industrial-01",name:"ArmFlex 6A",cat:"industrial",catName:"CÔNG NGHIỆP",icon:"🦿",desc:"Cánh tay 6 trục cho dây chuyền sản xuất.",price:2800000,rating:"5.0",place:"SHANGHAI / CN",tag:"VERIFIED"},
 {id:"event-01",name:"GuideBot Pro",cat:"event",catName:"SỰ KIỆN",icon:"🧑‍🚀",desc:"Robot lễ tân và tương tác tại sự kiện.",price:1600000,rating:"4.7",place:"HCMC / VN",tag:"NEW UNIT"},
 {id:"warehouse-02",name:"CleanRoute C3",cat:"warehouse",catName:"KHO VẬN",icon:"🛞",desc:"Lau sàn công nghiệp tự động, pin 8 giờ.",price:650000,rating:"4.8",place:"GUANGZHOU / CN",tag:"EFFICIENT"},
 {id:"service-02",name:"RoomMate R4",cat:"service",catName:"DỊCH VỤ",icon:"🧹",desc:"Giao đồ và phục vụ phòng tự động.",price:980000,rating:"4.6",place:"DANANG / VN",tag:"READY NOW"}
];
const state={cat:"all",query:"",orders:JSON.parse(localStorage.getItem("nexa-orders")||"[]")};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat(language==="vi"?"vi-VN":language,{style:language==="vi"?"decimal":"currency",currency:language==="vi"?"VND":"USD",maximumFractionDigits:language==="vi"?0:2}).format(n)+(language==="vi"?" đ":"");
function renderRobots(){const items=robots.filter(r=>(state.cat==="all"||state.cat===r.cat)&&`${r.name} ${r.desc} ${r.catName}`.toLowerCase().includes(state.query.toLowerCase()));$("#robotGrid").innerHTML=items.length?items.map(r=>`<article class="robot-card"><div class="robot-photo"><span>${r.icon}</span><em class="tag">${r.tag}</em></div><div class="robot-info"><h3>${r.name}</h3><p>${r.desc}</p><div class="robot-meta"><div><div class="price">${money(r.price)} <small>/ ${t("day")}</small></div><small>★ ${r.rating} · ${r.place}</small></div><div class="card-actions"><button class="detail-button" data-id="${r.id}">${t("details")}</button><button class="rent-button" data-id="${r.id}">${t("rent")}</button></div></div></div></article>`).join(""):`<div class="empty-state">${t("empty")}</div>`;document.querySelectorAll(".rent-button").forEach(b=>b.onclick=()=>booking(b.dataset.id));document.querySelectorAll(".detail-button").forEach(b=>b.onclick=()=>details(b.dataset.id))}
function details(id){const r=robots.find(x=>x.id===id);show(`<div class="kicker">UNIT PROFILE / ${r.catName}</div><h2>${r.name}<br><span>Thông số triển khai.</span></h2><div class="detail-hero"><span>${r.icon}</span><div><b>${r.tag}</b><small>★ ${r.rating} · ${r.place}</small></div></div><div class="spec-grid"><div><small>NHIỆM VỤ</small><b>${r.desc}</b></div><div><small>GIÁ THAM CHIẾU</small><b>${money(r.price)} / ngày</b></div><div><small>TRẠNG THÁI</small><b class="lime">SẴN SÀNG</b></div><div><small>HỖ TRỢ</small><b>Giao · lắp đặt · thu hồi</b></div></div><button class="neon-button" id="detailRent">ĐẶT THUÊ ĐƠN VỊ ↗</button>`);$("#detailRent").onclick=()=>booking(r.id)}
function show(html){$("#modalContent").innerHTML=html;$("#modalBackdrop").classList.remove("hidden")}function hide(){$("#modalBackdrop").classList.add("hidden")}
function booking(id){const r=robots.find(x=>x.id===id);show(`<div class="kicker">UNIT RESERVATION / ${r.catName}</div><h2>Đặt thuê<br><span>${r.name}</span></h2><p class="modal-intro">${r.desc} Đối tác vận chuyển, lắp đặt và thu hồi robot theo mã hợp đồng.</p><form id="bookForm"><div class="form-grid"><div class="field"><label>NGÀY BẮT ĐẦU</label><input required type="date" id="start"></div><div class="field"><label>THỜI LƯỢNG (NGÀY)</label><input required min="1" value="7" type="number" id="days"></div><div class="field full"><label>ĐỊA ĐIỂM TRIỂN KHAI</label><input required id="address" placeholder="Địa chỉ giao robot"></div><div class="field full"><label>NGƯỜI PHỤ TRÁCH</label><input required id="contact" placeholder="Họ tên · Email · Số điện thoại"></div></div><div class="summary"><span>ESTIMATED TOTAL</span><strong id="total">${money(r.price*7)}</strong></div><button class="neon-button" type="submit">TIẾP TỤC THANH TOÁN ↗</button></form>`);$("#start").value=new Date().toISOString().slice(0,10);$("#days").oninput=e=>$("#total").textContent=money(r.price*Math.max(1,Number(e.target.value)||1));$("#bookForm").onsubmit=e=>{e.preventDefault();payment(r,{days:Number($("#days").value),startDate:$("#start").value,address:$("#address").value,contact:$("#contact").value})}}
async function payment(r,details){const total=r.price*details.days;show(`<div class="kicker">SECURE CHECKOUT / MULTI-CURRENCY</div><h2>Kích hoạt<br><span>hợp đồng.</span></h2><p class="modal-intro">Chọn phương thức phù hợp. QR được tạo riêng cho đơn hàng và chỉ xác nhận sau khi cổng thanh toán báo thành công.</p><div class="summary"><span>${r.name} · ${details.days} NGÀY</span><strong>${money(total)}</strong></div><div class="payment-options"><button class="neon-button" id="payVnd">QR payOS / VND ↗</button><button class="neon-button secondary" id="payIntl">PayPal / CARD / USD ↗</button></div><div id="paymentResult"></div>`);$("#payVnd").onclick=()=>startPayment(r,details,"payos");$("#payIntl").onclick=()=>startPayment(r,details,"paypal")}
async function startPayment(r,details,provider){const result=$("#paymentResult");result.innerHTML='<p class="modal-intro">Đang tạo đơn hàng và payment session...</p>';try{const order=await api("/api/orders",{method:"POST",body:JSON.stringify({robotId:r.id,renterName:details.contact,renterEmail:details.email||details.contact,address:details.address,startDate:details.startDate,days:details.days})});const payment=await api(`/api/payments/${provider}`,{method:"POST",body:JSON.stringify({orderId:order.id,currency:"usd"})});result.innerHTML=`<div class="qr-payment"><img src="${payment.qrCode}" alt="QR thanh toán"><b>${provider==="payos"?"Quét QR payOS để thanh toán VND":"Mở PayPal hoặc quét QR để thanh toán quốc tế"}</b><a class="neon-button" href="${payment.checkoutUrl}" target="_blank" rel="noopener">MỞ TRANG THANH TOÁN ↗</a><small>Đơn ${order.contractCode} · ${payment.currency}</small></div>`;pollPayment(order.id,r,details,order)}catch(error){result.innerHTML=`<div class="success-box">PAYMENT UNAVAILABLE<br><span>${error.message}</span></div>`}}
const API_BASE=window.NEXA_API_URL||"https://api.nexarobot.cloud";
async function api(url,options={}){const response=await fetch(`${API_BASE}${url}`,{headers:{"Content-Type":"application/json"},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Backend chưa sẵn sàng.");return data}
async function capturePayPalReturn(){const params=new URLSearchParams(window.location.search);const orderId=params.get("orderId");const paypalOrderId=params.get("token");if(!orderId||!paypalOrderId)return;try{await api("/api/payments/paypal/capture",{method:"POST",body:JSON.stringify({orderId,paypalOrderId})});toast("✓ PayPal đã xác nhận thanh toán.");}catch(error){toast("PayPal chưa xác nhận: "+error.message)}}
function pollPayment(orderId,r,details,order){let checks=0;const timer=setInterval(async()=>{checks++;try{const status=await api(`/api/payments/status/${orderId}`);if(status.status==="paid"){clearInterval(timer);createOrder(r,details.days,r.price*details.days,order.contractCode)}}catch(error){if(checks>20)clearInterval(timer)}if(checks>20)clearInterval(timer)},4000)}
function createOrder(r,days,total,backendCode){const code=backendCode||`NX-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;state.orders.unshift({code,robot:r.name,days,total,date:new Date().toLocaleDateString("vi-VN"),status:"ĐANG VẬN HÀNH",receipt:""});localStorage.setItem("nexa-orders",JSON.stringify(state.orders));renderOrders();show(`<div class="success-box">✓ PAYMENT CONFIRMED<br><span>Đơn hàng đã gửi cho đối tác để chuẩn bị giao robot.</span></div><div class="kicker">CONTRACT IDENTIFIER</div><div class="contract-code">${code}</div><p class="modal-intro">Lưu mã hợp đồng. Đối tác phải xuất trình giấy xác nhận và mã này khi đến thu robot.</p><button class="neon-button" id="goOrders">XEM HỢP ĐỒNG ↓</button>`);$("#goOrders").onclick=()=>{hide();$("#orders").scrollIntoView()}}
function renderOrders(){const list=$("#ordersList");if(!state.orders.length){list.innerHTML='<div class="empty-state">NO ACTIVE CONTRACTS / Chọn một đơn vị để bắt đầu.</div>'}else{list.innerHTML=state.orders.map((o,i)=>`<article class="order-card"><div><h3>${o.robot}</h3><p>CONTRACT <strong>${o.code}</strong> · ${o.days} DAYS · ${o.date}</p>${o.receipt?`<p style="color:#ffb45d;margin-top:8px">PICKUP RECEIPT <strong>${o.receipt}</strong></p>`:""}</div><div class="order-actions"><span class="status">${o.status}</span>${o.receipt?"":`<button class="danger-button" data-index="${i}">CHẤM DỨT ↗</button>`}</div></article>`).join("");document.querySelectorAll(".danger-button").forEach(b=>b.onclick=()=>terminate(Number(b.dataset.index)))}renderAccount();renderAdmin()}
function renderAccount(){const profile=JSON.parse(localStorage.getItem("nexa-profile")||"null");if(profile){$("#accountName").textContent=profile.name;$("#accountEmail").textContent=profile.email}$("#accountOrders").textContent=state.orders.length;$("#accountActive").textContent=state.orders.filter(o=>!o.receipt).length;$("#accountClosed").textContent=state.orders.filter(o=>o.receipt).length}
function renderAdmin(){$("#adminRobotCount").textContent=`${robots.length.toString().padStart(2,"0")} UNITS`;$("#adminOrderCount").textContent=`${state.orders.length.toString().padStart(2,"0")} ORDERS`;$("#adminRobots").innerHTML=robots.map(r=>`<div class="admin-row"><span>${r.icon}</span><b>${r.name}</b><small>${r.catName}</small><i>ACTIVE</i></div>`).join("");$("#adminOrders").innerHTML=state.orders.length?state.orders.map(o=>`<div class="admin-row"><span>↗</span><b>${o.code}</b><small>${o.robot}</small><i>${o.status}</i></div>`).join(""):'<div class="admin-empty">Chưa có đơn hàng.</div>'}
function terminate(i){const o=state.orders[i];show(`<div class="kicker">PICKUP REQUEST / ${o.code}</div><h2>Phát hành<br><span>phiếu thu hồi?</span></h2><p class="modal-intro">Khách hàng xác nhận chấm dứt. NEXA sẽ phát hành phiếu cho cả hai bên. Đối tác phải xuất trình giấy xác nhận và mã hợp đồng khi đến thu.</p><div class="summary"><span>CONTRACT</span><strong>${o.code}</strong></div><button class="neon-button" id="confirm">PHÁT HÀNH PHIẾU THU HỒI ↗</button>`);$("#confirm").onclick=()=>{const receipt=`PK-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;o.receipt=receipt;o.status="CHỜ ĐỐI TÁC THU HỒI";localStorage.setItem("nexa-orders",JSON.stringify(state.orders));renderOrders();show(`<div class="success-box">✓ PICKUP PROTOCOL ISSUED<br><span>Thông tin đã gửi cho khách hàng và đối tác.</span></div><div class="receipt">MÃ PHIẾU THU HỒI<br><strong>${receipt}</strong><br><br>MÃ HỢP ĐỒNG ĐỐI CHIẾU<br><strong>${o.code}</strong><br><br>Đối tác xuất trình giấy xác nhận + mã hợp đồng khi đến thu.</div><button class="neon-button" id="done">ĐÃ HIỂU</button>`);$("#done").onclick=hide}}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{state.cat=b.dataset.category;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));renderRobots()});$("#searchInput").oninput=e=>{state.query=e.target.value;renderRobots()};$("#closeModal").onclick=hide;$("#modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")hide()};
$("#openPartner").onclick=()=>show(`<div class="kicker">PARTNER ONBOARDING</div><h2>Kết nối<br><span>đội robot.</span></h2><p class="modal-intro">Tạo ví đối tác và khai báo email PayPal để nhận tiền khi rút.</p><div class="field"><label>TÊN ĐỐI TÁC</label><input id="partnerNameInput" placeholder="Tên cá nhân hoặc đơn vị"></div><div class="field"><label>EMAIL LIÊN HỆ</label><input id="partnerEmailInput" type="email" placeholder="you@example.com"></div><div class="field"><label>EMAIL PAYPAL NHẬN TIỀN</label><input id="partnerPaypalInput" type="email" placeholder="paypal@example.com"></div><button class="neon-button" id="partnerSubmit">TẠO VÍ ĐỐI TÁC ↗</button>`);
$("#editAccount").onclick=()=>show(`<div class="kicker">RENTER PROFILE</div><h2>Cập nhật<br><span>tài khoản.</span></h2><div class="field"><label>HỌ TÊN / TÊN DOANH NGHIỆP</label><input id="profileName" placeholder="Nguyễn Văn A"></div><div class="field"><label>EMAIL NHẬN THÔNG BÁO</label><input id="profileEmail" type="email" placeholder="you@company.com"></div><button class="neon-button" id="saveProfile">LƯU HỒ SƠ ↗</button>`);
$("#openAssistant").onclick=()=>show(`<div class="kicker">NEXA AI / BASIC ASSISTANT</div><h2>Trợ lý<br><span>triển khai robot.</span></h2><p class="modal-intro">Tôi có thể gợi ý nhanh mô hình phù hợp dựa trên nhu cầu của bạn.</p><div class="field"><label>BẠN MUỐN THỰC HIỆN VIỆC GÌ?</label><input id="aiQuestion" placeholder="Ví dụ: cần robot cho kho 7 ngày"></div><button class="neon-button" id="askAi">PHÂN TÍCH NHU CẦU ↗</button><div id="aiAnswer"></div>`);
document.addEventListener("click",e=>{if(e.target.id==="partnerSubmit"){registerPartner()}if(e.target.id==="partnerWithdraw"){withdrawPartner()}if(e.target.id==="saveProfile"){const profile={name:$("#profileName").value.trim()||"Khách hàng NEXA",email:$("#profileEmail").value.trim()||"Chưa cập nhật email"};localStorage.setItem("nexa-profile",JSON.stringify(profile));renderAccount();hide();toast("✓ Hồ sơ đã được cập nhật.")}if(e.target.id==="askAi"){const q=$("#aiQuestion").value.toLowerCase();const result=q.includes("kho")||q.includes("vận chuyển")?robots.find(r=>r.id==="warehouse-01"):q.includes("nhà hàng")||q.includes("phục vụ")?robots.find(r=>r.id==="service-01"):q.includes("sản xuất")||q.includes("công nghiệp")?robots.find(r=>r.id==="industrial-01"):robots[0];$("#aiAnswer").innerHTML=`<div class="ai-answer">GỢI Ý ĐƠN VỊ<br><strong>${result.icon} ${result.name}</strong><br><small>${result.desc} Giá tham chiếu ${money(result.price)}/ngày.</small><button class="detail-button ai-rent" data-id="${result.id}">XEM CHI TIẾT ↗</button></div>`;document.querySelector(".ai-rent").onclick=()=>details(result.id)}}); 
async function registerPartner(){try{const response=await api("/api/partners/register",{method:"POST",body:JSON.stringify({name:$("#partnerNameInput").value,email:$("#partnerEmailInput").value,paypalEmail:$("#partnerPaypalInput").value})});localStorage.setItem("nexa-partner-token",response.accessToken);hide();await loadPartner();toast("✓ Ví đối tác đã sẵn sàng.");}catch(error){toast(error.message)}}
async function loadPartner(){const token=localStorage.getItem("nexa-partner-token");if(!token)return;try{const p=await api("/api/partners/me",{headers:{"x-partner-token":token}});$("#partnerName").textContent=p.name;$("#partnerPaypal").textContent=p.paypalEmail||"Chưa có PayPal email";$("#partnerAvailable").textContent=money(p.availableBalanceVnd);$("#partnerPending").textContent=money(p.pendingBalanceVnd);$("#partnerWithdrawn").textContent=money(p.withdrawnBalanceVnd)}catch(error){localStorage.removeItem("nexa-partner-token")}}
async function withdrawPartner(){const token=localStorage.getItem("nexa-partner-token");if(!token)return show('<div class="success-box">Hãy đăng ký tài khoản đối tác trước.</div>');try{const result=await api("/api/partners/withdraw",{method:"POST",headers:{"x-partner-token":token},body:"{}"});await loadPartner();show(`<div class="success-box">✓ YÊU CẦU RÚT TIỀN ĐÃ GỬI<br><span>PayPal batch ${result.paypalBatchId}</span></div>`)}catch(error){show(`<div class="success-box">KHÔNG THỂ RÚT TIỀN<br><span>${error.message}</span></div>`)}}
function toast(message){$("#toast").textContent=message;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),3000)}
$("#languageSelect").onchange=e=>{language=e.target.value;localStorage.setItem("nexa-language",language);applyLanguage();renderOrders();toast("✓ "+(language==="vi"?"Đã đổi ngôn ngữ":"Language updated"))};
applyLanguage();renderOrders();loadPartner();capturePayPalReturn();
